# Generated by Django 6.0 on 2026-05-01 16:26

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_supplier_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        # First make date_received nullable to handle existing data
        migrations.RunSQL(
            "UPDATE integrations_supplier SET date_received = CURRENT_DATE WHERE date_received IS NULL;",
            "-- Reverse operation not needed"
        ),
        migrations.AlterField(
            model_name='supplier',
            name='date_received',
            field=models.DateField(),
        ),
    ]
