# Generated by Django 6.0 on 2026-05-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_cylindertransaction_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtype',
            name='category',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('accessory', 'Accessory')], max_length=20),
        ),
    ]
