# Generated by Django 6.0 on 2026-05-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_itemtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cylinderinventory',
            name='category',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cylindertransaction',
            name='category',
            field=models.CharField(choices=[('cylinder', 'Cylinder'), ('accessory', 'Accessory')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
