# Generated by Django 6.0 on 2026-06-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_customerprofile_customerpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpurchase',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='customerpurchase',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='CustomerPurchase',
        ),
    ]
